import uuid
from urllib.parse import urlparse

import boto3
from botocore.config import Config

from app.core.config import settings


def get_r2_client():
    return boto3.client(
        "s3",
        endpoint_url=settings.R2_ENDPOINT_URL,
        aws_access_key_id=settings.R2_ACCESS_KEY_ID,
        aws_secret_access_key=settings.R2_SECRET_ACCESS_KEY,
        config=Config(signature_version="s3v4"),
        region_name="auto",
    )


def upload_file(
    file_bytes: bytes,
    filename: str,
    content_type: str,
    folder: str = "attachments",
) -> str:
    """
    Uploads file to R2, returns the public URL.
    Key format: {folder}/{uuid}_{filename}
    """
    client = get_r2_client()
    key = f"{folder}/{uuid.uuid4()}_{filename}"
    client.put_object(
        Bucket=settings.R2_BUCKET_NAME,
        Key=key,
        Body=file_bytes,
        ContentType=content_type,
    )
    return f"{settings.R2_PUBLIC_URL}/{key}"


def upload_bytes_to_r2(
    file_bytes: bytes,
    filename: str,
    content_type: str,
) -> str:
    """
    Upload raw bytes to R2 with the provided key and return the public URL.
    """
    client = get_r2_client()
    client.put_object(
        Bucket=settings.R2_BUCKET_NAME,
        Key=filename,
        Body=file_bytes,
        ContentType=content_type,
    )
    return f"{settings.R2_PUBLIC_URL}/{filename}"


def delete_file_by_public_url(file_url: str) -> None:
    """Delete an object from R2 using a public URL generated by this service."""
    base_url = settings.R2_PUBLIC_URL.rstrip("/")
    if not base_url:
        return

    key: str | None = None
    if file_url.startswith(f"{base_url}/"):
        key = file_url[len(base_url) + 1 :]
    else:
        parsed = urlparse(file_url)
        key = parsed.path.lstrip("/") or None

    if not key:
        return

    client = get_r2_client()
    client.delete_object(Bucket=settings.R2_BUCKET_NAME, Key=key)
